### Create a new PhotoBpx
POST http://localhost:8000/api/photo-box
Content-Type: application/json

{
  "owner_id": "62d9d5cffdb13a0a68cb45b0",
  "firebase_root_folder_name": "marcs-pics",
  "firebase_folder_name": "usa2022",
  "display_name": "Meine U.S.A-Reise 2022",
  "description": "Beschreibung folgt",
  "tags": [
    "USA",
    "Groundhopping",
    "2022"
  ]
}


### Update a PhotoBox by id.
PUT http://localhost:8000/api/photo-box/62dc005ff610b93f275edad2
Content-Type: application/json

{
  "firebase_root_folder_name": "marcs-films",
  "firebase_folder_name": "comingsoon2023",
  "display_name": "Korea-Reise 2023",
  "description": "Beschreibung folgt, wenn ich die Reise angetreten habe...",
  "tags": [
    "Korea",
    "food tour",
    "2023"
  ]
}


### Get all PhotoBoxes.
GET http://localhost:8000/api/photo-boxes

### Get a PhotoBox by its id.
GET http://localhost:8000/api/photo-box/62dc005ff610b93f275edad2
