### Get all SharedCollections.
GET http://localhost:8000/api/collections


### Get a SharedCollection by its hash.
GET http://localhost:8000/api/collection/?hash=R5etV2qtJ9SCsIZFV0E775N8x


### Get a password protexted SharedCollection by its hash with password.
GET http://localhost:8000/api/collection/?hash=s2NfOpDatUXjPhqWO4joLnMIZ&password=test
