### API endpoints for User


### Create a User
# @name lets you save the request in a variable
# @name newUser
POST http://localhost:8000/api/user
Content-Type: application/json

{
  "nickname": "Marc",
  "email": "test@test.de",
  "password": "crypt-me",
  "role": "Admin"
}


### Get a User by id
# Variable only works if the previous request created a User.
@lastAddedUserId={{newUser.response.body.$.insertedId.$oid}}
GET http://localhost:8000/api/user/{{lastAddedUserId}}

### Test for invalid ObjectId - returns 500
GET http://localhost:8000/api/user/not-a-object-id


### Update a User's nickname or email
# Variable only works if the previous request created a User.
@lastAddedUserId={{newUser.response.body.$.insertedId.$oid}}
PUT http://localhost:8000/api/user/{{lastAddedUserId}}
Content-Type: 'application/json'

{
  "nickname": "Marc the Shark",
  "email": "cool@hool.me"
}


### Delete a User by id
# Variable only works if the previous request created a User.
@lastAddedUserId={{newUser.response.body.$.insertedId.$oid}}
DELETE http://localhost:8000/api/user/{{lastAddedUserId}}


### Get all Users.
GET http://localhost:8000/api/users
